### ISSUE TITLE
Relationship to zigzagboomerang

### ISSUE THREAD

**Issue by EvoArt** [162348/PDMPFlux.jl#2]
Hi there. I was just wondering how this package relates to Zigzagboomerang.jl. i.e. is this a replacement, or something that works with that package?

Thanks

**Comment by 162348** [comment]
Hi, and thank you for your interest to this new project. Unfortunately, it has nothing to do with `ZigZagBoomerang.jl` (yet). It may be great to consider integrating with or providing an API for `ZigZagBoomerang.jl` in future updates.

The initial goal was to improve the core technique of automatic Poisson thinning, as discussed in [this paper](https://arxiv.org/abs/2408.03682), which is too recent a technique to be supported in `ZigZagBoomerang.jl`. For this reason among others, authoring a package from scratch was a natural choice for me.

**Comment by EvoArt** [comment]
No worries. I work with quite messy (ecological) data, so I'm always interested in inference methods! Glad to see a Julia implementation. Thanks for your work.

**Comment by EvoArt** [comment]
No worries. I work with quite messy (ecological) data, so I'm always interested in inference methods! Glad to see a Julia implementation. Thanks for your work.

**Comment by 162348** [comment]
Thank you! I hope this package can be of some help some day!
